### PR TITLE
fixed bugs that useing in browserify will borken

### PR DESCRIPTION
**Pull request by soliury**
Now it works well with browserify.

### CODE REVIEW

**Comment by RyanMullins** [comment]
I've integrated these changes as part of some other work I was already doing. They'll be included in v2.1.3. 

I want to develop some unit tests for this sort of thing. I'll close this issue, and #18 when I have finished those tests.

**Comment by soliury** [comment]
OK, BTW, another questions about hammer.js.  When I use hm-panright, I find that my web-app can't scroll in mobile browsers.  Do you know how to solve it ?

**Comment by RyanMullins** [comment]
There was a similar problem reported in #16. I am thinking this is most likely a problem in my code (with the recognizer not being initialized to support a direction) but it could be a bigger issue with Hammer. For the time being, try adding in an explicit directions definition using the hm-recognizer-options directive, like this:

```html
<div hm-panright="someFunction" hm-recognizer-options='[{""type":"pan","directions":"DIRECTION_RIGHT"}]'></div>
```

**Comment by soliury** [comment]
No, it failed, it doesn't work.

**Comment by RyanMullins** [comment]
I have another issue tracing (#20) that is reporting the same problem with `hm-panright`. I'll keep you both posted as I work on a fix.

**Pull request closed without merging**
